# Generated by Django 5.2.6 on 2025-11-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_subscriptionplan_reservation_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='color_theme',
            field=models.CharField(default='primary', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='perks',
            field=models.JSONField(default=list),
        ),
    ]
