# Generated by Django 5.2.8 on 2025-11-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_reservation_checked_in_alter_reservation_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
